[project]
name = "cr-model-armor"
version = "0.1.0"
description = "Global Safety Guardrail Server"
readme = "README.md"
requires-python = "==3.13.5"
dependencies = [
    "af-aidevs==0.1.6",
    "fastapi==0.136.1",
    "google-genai==1.74.0",
    "pydantic==2.13.4",
    "python-frontmatter==1.1.0",
    "uvicorn==0.46.0",
]

[[tool.uv.index]]
name = "gar"
url = "https://europe-west6-python.pkg.dev/af-aidevs/python-packages/simple/"
explicit = true

[tool.uv.sources]
af-aidevs = { index = "gar" }

